export { default as Login } from './views/Login.vue'
export { default as Register } from './views/Register.vue'
export { default as RegisterConfirm } from './views/RegisterConfirm.vue'
export { default as RegisterVerify } from './views/RegisterVerify.vue'
export { default as DeleteAccountSuccess } from './views/DeleteAccountSuccess.vue'
export { default as ResetPassword } from './views/ResetPassword.vue'
export { default as PasswordVerify } from './views/PasswordVerify.vue'
